"""change_cve_id_to_json_array

Revision ID: 26cbcfade256
Revises: 8848bf82662d
Create Date: 2025-08-09 16:12:33.094875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26cbcfade256'
down_revision: Union[str, Sequence[str], None] = '8848bf82662d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_ip_key'), 'assets', type_='unique')
    
    # Convert existing string CVE IDs to JSON arrays
    connection = op.get_bind()
    
    # First, add a temporary column
    op.add_column('findings', sa.Column('cve_id_temp', sa.JSON(), nullable=True))
    
    # Convert existing data: string -> JSON array
    connection.execute(sa.text("""
        UPDATE findings 
        SET cve_id_temp = CASE 
            WHEN cve_id IS NULL OR cve_id = '' THEN NULL
            WHEN cve_id LIKE '%,%' THEN 
                -- Split comma-separated CVEs into JSON array
                to_json(string_to_array(trim(cve_id), ','))
            ELSE 
                -- Single CVE becomes JSON array with one element
                to_json(ARRAY[trim(cve_id)])
        END
    """))
    
    # Drop old column and rename temp column
    op.drop_column('findings', 'cve_id')
    op.alter_column('findings', 'cve_id_temp', new_column_name='cve_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('findings', 'cve_id',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('assets_ip_key'), 'assets', ['ip'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
