"""enhance_schema_with_constraints_and_indexes

Revision ID: 8848bf82662d
Revises: 3d224909b3e7
Create Date: 2025-08-07 10:30:57.709109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8848bf82662d"
down_revision: Union[str, Sequence[str], None] = "3d224909b3e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first, then make them NOT NULL
    op.add_column(
        "assets",
        sa.Column("status", sa.String(), nullable=True, server_default="active"),
    )
    op.add_column(
        "assets",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=True, server_default=sa.text("NOW()")
        ),
    )

    # Update existing rows with default values
    op.execute("UPDATE assets SET status = 'active' WHERE status IS NULL")
    op.execute("UPDATE assets SET updated_at = created_at WHERE updated_at IS NULL")

    # Now make the columns NOT NULL
    op.alter_column("assets", "status", nullable=False)
    op.alter_column("assets", "updated_at", nullable=False)
    op.alter_column("assets", "ip", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "assets", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index("idx_assets_created_at", "assets", ["created_at"], unique=False)
    op.create_index("idx_assets_status", "assets", ["status"], unique=False)
    op.create_index("idx_assets_updated_at", "assets", ["updated_at"], unique=False)
    # Add findings discovered_at column with default
    op.add_column(
        "findings",
        sa.Column(
            "discovered_at",
            sa.DateTime(),
            nullable=True,
            server_default=sa.text("NOW()"),
        ),
    )

    # Update existing rows - use the scan_date from the related openvas_scan
    op.execute("""
        UPDATE findings 
        SET discovered_at = (
            SELECT scan_date 
            FROM openvas_scans 
            WHERE openvas_scans.id = findings.openvas_scan_id
        ) 
        WHERE discovered_at IS NULL
    """)

    # Make discovered_at NOT NULL
    op.alter_column("findings", "discovered_at", nullable=False)
    op.alter_column(
        "findings", "openvas_scan_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("findings", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("findings", "severity", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("findings", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index("idx_findings_cve_id", "findings", ["cve_id"], unique=False)
    op.create_index(
        "idx_findings_discovered_at", "findings", ["discovered_at"], unique=False
    )
    op.create_index(
        "idx_findings_openvas_scan_id", "findings", ["openvas_scan_id"], unique=False
    )
    op.create_index("idx_findings_severity", "findings", ["severity"], unique=False)
    op.create_index("idx_findings_status", "findings", ["status"], unique=False)
    # Add nmap_scans columns with defaults
    op.add_column(
        "nmap_scans",
        sa.Column("status", sa.String(), nullable=True, server_default="completed"),
    )
    op.add_column("nmap_scans", sa.Column("scan_duration", sa.Float(), nullable=True))
    op.add_column("nmap_scans", sa.Column("command_used", sa.String(), nullable=True))

    # Update existing rows
    op.execute("UPDATE nmap_scans SET status = 'completed' WHERE status IS NULL")

    # Make status NOT NULL
    op.alter_column("nmap_scans", "status", nullable=False)
    op.alter_column(
        "nmap_scans", "asset_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "nmap_scans", "scan_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.create_index("idx_nmap_scans_asset_id", "nmap_scans", ["asset_id"], unique=False)
    op.create_index(
        "idx_nmap_scans_scan_date", "nmap_scans", ["scan_date"], unique=False
    )
    op.create_index("idx_nmap_scans_status", "nmap_scans", ["status"], unique=False)
    # Add openvas_scans columns with defaults
    op.add_column(
        "openvas_scans",
        sa.Column("status", sa.String(), nullable=True, server_default="completed"),
    )
    op.add_column(
        "openvas_scans", sa.Column("scan_duration", sa.Float(), nullable=True)
    )
    op.add_column("openvas_scans", sa.Column("scan_config", sa.String(), nullable=True))

    # Update existing rows
    op.execute("UPDATE openvas_scans SET status = 'completed' WHERE status IS NULL")

    # Make status NOT NULL
    op.alter_column("openvas_scans", "status", nullable=False)
    op.alter_column(
        "openvas_scans", "asset_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "openvas_scans",
        "scan_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_index(
        "idx_openvas_scans_asset_id", "openvas_scans", ["asset_id"], unique=False
    )
    op.create_index(
        "idx_openvas_scans_scan_date", "openvas_scans", ["scan_date"], unique=False
    )
    op.create_index(
        "idx_openvas_scans_status", "openvas_scans", ["status"], unique=False
    )

    # Add check constraints
    op.create_check_constraint(
        "chk_asset_status",
        "assets",
        "status IN ('active', 'inactive', 'decommissioned')",
    )
    op.create_check_constraint(
        "chk_nmap_scan_status",
        "nmap_scans",
        "status IN ('running', 'completed', 'failed', 'cancelled')",
    )
    op.create_check_constraint(
        "chk_openvas_scan_status",
        "openvas_scans",
        "status IN ('running', 'completed', 'failed', 'cancelled')",
    )
    op.create_check_constraint(
        "chk_finding_severity",
        "findings",
        "severity IN ('Low', 'Medium', 'High', 'Critical')",
    )
    op.create_check_constraint(
        "chk_finding_status",
        "findings",
        "status IN ('NOT_VALIDATED', 'VALIDATED', 'NOT_CONFIRM', 'FALSE_POSITIVE')",
    )
    op.create_check_constraint(
        "chk_finding_cvss_score",
        "findings",
        "cvss_score IS NULL OR (cvss_score >= 0.0 AND cvss_score <= 10.0)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop check constraints
    op.drop_constraint("chk_finding_cvss_score", "findings", type_="check")
    op.drop_constraint("chk_finding_status", "findings", type_="check")
    op.drop_constraint("chk_finding_severity", "findings", type_="check")
    op.drop_constraint("chk_openvas_scan_status", "openvas_scans", type_="check")
    op.drop_constraint("chk_nmap_scan_status", "nmap_scans", type_="check")
    op.drop_constraint("chk_asset_status", "assets", type_="check")

    op.drop_index("idx_openvas_scans_status", table_name="openvas_scans")
    op.drop_index("idx_openvas_scans_scan_date", table_name="openvas_scans")
    op.drop_index("idx_openvas_scans_asset_id", table_name="openvas_scans")
    op.alter_column(
        "openvas_scans",
        "scan_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "openvas_scans", "asset_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("openvas_scans", "scan_config")
    op.drop_column("openvas_scans", "scan_duration")
    op.drop_column("openvas_scans", "status")
    op.drop_index("idx_nmap_scans_status", table_name="nmap_scans")
    op.drop_index("idx_nmap_scans_scan_date", table_name="nmap_scans")
    op.drop_index("idx_nmap_scans_asset_id", table_name="nmap_scans")
    op.alter_column(
        "nmap_scans", "scan_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("nmap_scans", "asset_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("nmap_scans", "command_used")
    op.drop_column("nmap_scans", "scan_duration")
    op.drop_column("nmap_scans", "status")
    op.drop_index("idx_findings_status", table_name="findings")
    op.drop_index("idx_findings_severity", table_name="findings")
    op.drop_index("idx_findings_openvas_scan_id", table_name="findings")
    op.drop_index("idx_findings_discovered_at", table_name="findings")
    op.drop_index("idx_findings_cve_id", table_name="findings")
    op.alter_column("findings", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("findings", "severity", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("findings", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "findings", "openvas_scan_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("findings", "discovered_at")
    op.drop_index("idx_assets_updated_at", table_name="assets")
    op.drop_index("idx_assets_status", table_name="assets")
    op.drop_index("idx_assets_created_at", table_name="assets")
    op.alter_column(
        "assets", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("assets", "ip", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("assets", "updated_at")
    op.drop_column("assets", "status")
    # ### end Alembic commands ###
